### ISSUE TITLE
减少 Jar 包大小

### ISSUE THREAD

**Issue by Erzbir** [Stonewuu/halo-plugin-sitepush#13]
## 问题:
在pr #10 之后, 因为用了谷歌的 oauth2 库, 导致大小从原本的 3 MB 上升到了 8 MB, 我认为这与此插件功能极其不符

## 解决:
去掉 google oauth2 库, 自己生成 jwt

**Comment by Erzbir** [comment]
代码已经完成, 稍后提交 pr

**Comment by JohnNiang** [comment]
https://github.com/Stonewuu/halo-plugin-sitepush/blob/edbafad307e93032249b6b1b72b3c56c6d26950a/build.gradle#L20

`hutool-all` 依赖中似乎包含 `hutool-jwt` 模块，能否复用，降低维护成本。

**Comment by Erzbir** [comment]
> https://github.com/Stonewuu/halo-plugin-sitepush/blob/edbafad307e93032249b6b1b72b3c56c6d26950a/build.gradle#L20
> 
> 
> 
> `hutool-all` 依赖中似乎包含 `hutool-jwt` 模块，能否复用，降低维护成本。

那感觉不使用 `hutool-all`，只引入 `hutool-json` 和 `hutool-http` 更合适，因为目前只有谷歌推送会用到 jwt

**Comment by Erzbir** [comment]
已在此 pr #18 中将 `hutool-all` 依赖替换为 `hutool-json` 和 `hutool-http`

**Comment by JohnNiang** [comment]
建议一个 PR 只做一件事情。

**Comment by Erzbir** [comment]
> 建议一个 PR 只做一件事情。

确实如此 👍

**Comment by Erzbir** [comment]
已在此 # 中将 hutool-all 依赖替换为 hutool-json 和 hutool-http
