### ISSUE TITLE
推送日志页面建议

### ISSUE THREAD

**Issue by wxyShine** [Stonewuu/halo-plugin-sitepush#17]
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/42802152/6a7018f2-b108-45be-bd53-1843b071fd4c)

增加分页 或者日期筛选条件默认当天.   数据多的时候容易造成浏览器卡死

**Comment by Erzbir** [comment]
代码已完成，明天提交

**Comment by wxyShine** [comment]
可以加个一键清空日志吗 或者手动删除

**Comment by Erzbir** [comment]
> 可以加个一键清空日志吗 或者手动删除

另开一个 issue 吧
