### ISSUE TITLE
推送 sitemap 中的链接

### ISSUE THREAD

**Issue by Erzbir** [Stonewuu/halo-plugin-sitepush#22]
我在考虑要不要让插件推送 sitemap 中的内容 @Stonewuu 

顺带一提, 可以把我加入仓库协作者吗

**Comment by Stonewuu** [comment]
> 我在考虑要不要让插件推送 sitemap 中的内容 @Stonewuu
Sitemap中确实包含除开文章和自定义页面的其他页面，可以考虑增加一个开关提供给用户选择

> 顺带一提, 可以把我加入仓库协作者吗
好的，已经添加了
