### ISSUE TITLE
有人成功过吗？

### ISSUE THREAD

**Issue by WaterSunMount** [Stonewuu/halo-plugin-sitepush#26]
## 必应报错：
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/75781948/b683ff5b-3b48-46c6-83cb-e2cabd072627)
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/75781948/52ddcef3-9ad6-4150-afc3-988840b4c907)

## 百度报错
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/75781948/bd6f3661-6fc0-47c5-8df2-fa5cf3aff7b5)
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/75781948/312456cc-8453-4b01-ad41-c01a09e9c2ba)

**Comment by Erzbir** [comment]
报什么错可以在halo后台看一下吗，给个日志

**Comment by Erzbir** [comment]
也可尝试重启插件之后再进行验证，试试看

**Comment by WaterSunMount** [comment]
先睡吧，熬不住了😂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月05日 03:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Stonewuu/halo-plugin-sitepush] 有人成功过吗？ (Issue #26) |

报什么错可以在halo后台看一下吗，给个日志

**Comment by Erzbir** [comment]
> 先睡吧，熬不住了😂
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年11月05日 03:13 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [Stonewuu/halo-plugin-sitepush] 有人成功过吗？ (Issue #26) | 报什么错可以在halo后台看一下吗，给个日志 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

因为我这边是没有问题的, 我建议是配置好后重启一下插件

如果插件日志显示推送失败, 提供一下 halo 的运行日志

**Comment by WaterSunMount** [comment]
我看了没有错误日志
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/75781948/ab9af9d7-505f-40b4-b8e2-9e0a2ce398d5)
不过貌似被限流了，我明天再测试看看

**Comment by Erzbir** [comment]
> 我看了没有错误日志 ![image](https://user-images.githubusercontent.com/75781948/280501741-ab9af9d7-505f-40b4-b8e2-9e0a2ce398d5.png) 不过貌似被限流了，我明天再测试看看

日志上显示 366 个链接成功推送了, 似乎没有问题. 你的站点可以给一下吗, 我看看有没有对应的 tag

**Comment by WaterSunMount** [comment]
> > 我看了没有错误日志 ![image](https://user-images.githubusercontent.com/75781948/280501741-ab9af9d7-505f-40b4-b8e2-9e0a2ce398d5.png) 不过貌似被限流了，我明天再测试看看
> 
> 日志上显示 366 个链接成功推送了, 似乎没有问题. 你的站点可以给一下吗, 我看看有没有对应的 tag

https://blog.litecode.top/

**Comment by Erzbir** [comment]
> https://blog.litecode.top/

我这边无法访问

**Comment by Erzbir** [comment]
没有问题的话稍后我就关闭 Issue 了
