### ISSUE TITLE
百度推送失败，日志里显示Pushing to baidu Result: null

### ISSUE THREAD

**Issue by niujunbo119** [Stonewuu/halo-plugin-sitepush#28]
百度推送失败，日志里显示Pushing to baidu Result: null
![Snipaste_2023-12-08_21-17-19](https://github.com/Stonewuu/halo-plugin-sitepush/assets/43308469/b65dd518-9d88-4a77-8556-522668e669bc)

**Comment by niujunbo119** [comment]
配置在这里
![Snipaste_2023-12-08_21-18-53](https://github.com/Stonewuu/halo-plugin-sitepush/assets/43308469/bb7e8721-142b-477c-8590-be5b234becd8)

**Comment by Erzbir** [comment]
看看百度限额到没

**Comment by niujunbo119** [comment]
确实是进入限额到了。我后面再试一下，调整调整。

**Comment by Erzbir** [comment]
这里为 null 是代码 bug 导致, 已修复 #46
