### ISSUE TITLE
大佬求助，我的sitemap.xml无法在google search上的站点地图中被识别。（求助）

### ISSUE THREAD

**Issue by MicroMatrixOrg** [Stonewuu/halo-plugin-sitepush#30]
大佬求助，我的sitemap.xml无法在google search上的站点地图中被识别。还有个问题，在推送日志那里显示不出来日志。我看了下报错是由于接口请求大于1秒。
{
    "message": "timeout of 1000ms exceeded",
    "name": "AxiosError",
    "stack": "AxiosError: timeout of 1000ms exceeded\n    at c.ontimeout (https://blog.micromatrix.cf/apis/api.console.halo.run/v1alpha1/plugins/-/bundle.js?t=dsfsdexf:gd:asdf)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 1000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "X-XSRF-TOKEN": "9ddddxxxxxx"
        },
        "baseURL": "/",
        "url": "/apis/sitepush.halo.run/v1alpha1/pushLogs",
        "method": "get",
        "params": {
            "page": 1,
            "size": 20
        }
    },
    "code": "ECONNABORTED",
    "status": null
}
能不能加一个设置，设置大于1秒也可以显示啊

**Comment by Erzbir** [comment]
现在呢

**Comment by MicroMatrixOrg** [comment]
> 现在呢

可以了，现在能显示出来了，Google推送也正常了
