### ISSUE TITLE
优化页面显示

### ISSUE THREAD

**Issue by adozhao** [Stonewuu/halo-plugin-sitepush#31]
UI可以优化下，给个padding也行~
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/23180747/5e10ff33-60d3-460c-8692-19a5c8593393)

作者大大辛苦了，感谢贡献这么优秀的插件！

**Comment by ruibaby** [comment]
我有兴趣优化一下，可以 assign 给我吗

**Comment by Erzbir** [comment]
> 我有兴趣优化一下，可以 assign 给我吗

感谢❤️

**Comment by adozhao** [comment]
我是前端开发，刚开始用Halo，后面我也会学习下插件开发
