### ISSUE TITLE
功能优化建议

### ISSUE THREAD

**Issue by adozhao** [Stonewuu/halo-plugin-sitepush#37]
提交失败会不断重试，这是一夜的量，建议失败之后逐渐延缓提交频率，例如1m、15m、1h、6h、1d... 
现在这个提交失败处理，生怕把halo干坏掉，不知道halo有没有对插件做隔离，毕竟设计上是要考虑隔离的

![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/23180747/b4baf6d1-0ae7-4751-a853-61b856f1c4f8)

**Comment by Erzbir** [comment]
确实，过几天加上限制配置，先关闭谷歌的推送吧

**Comment by MicroMatrixOrg** [comment]
> 确实，过几天加上限制配置，先关闭谷歌的推送吧

大佬，我使用docker搭建的halo,然后我宿主机上挂了xray代理。docker里面可以访问google，但是一直提交失败。你是怎么弄google的提交的

**Comment by MicroMatrixOrg** [comment]
> > > 确实，过几天加上限制配置，先关闭谷歌的推送吧
> > 
> > 
> > 大佬，我使用docker搭建的halo,然后我宿主机上挂了xray代理。docker里面可以访问google，但是一直提交失败。你是怎么弄google的提交的
> 
> 我也是挂了代理没用~

![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/21361701/59a03452-c358-4213-a4d1-5ada48a26cd5)
我是这么设置的，一开始貌似成功过，时间有点长，我记不太清了

**Comment by Erzbir** [comment]
> > 确实，过几天加上限制配置，先关闭谷歌的推送吧
> 
> 大佬，我使用docker搭建的halo,然后我宿主机上挂了xray代理。docker里面可以访问google，但是一直提交失败。你是怎么弄google的提交的

是网口代理吗

**Comment by adozhao** [comment]
百度的提交有用吗？我看百度里面没有我的任何提交记录，一周了都~

**Comment by MicroMatrixOrg** [comment]
> > > 确实，过几天加上限制配置，先关闭谷歌的推送吧
> > 
> > 
> > 大佬，我使用docker搭建的halo,然后我宿主机上挂了xray代理。docker里面可以访问google，但是一直提交失败。你是怎么弄google的提交的
> 
> 是网口代理吗

我是直接设置在docker-compose.yml文件中的
```json
    environment:
      - http_proxy=http://172.17.0.1:8889
      - https_proxy=http://172.17.0.1:8889
```

`http://172.17.0.1`是docker的ip，我是先宿主机开代理，然后再给docker代理。服务器挂代理的[文章1](https://blog.micromatrix.cf/archives/VXY32avW) [文章2](https://micromatrix.eu.org/article/20231109)

**Comment by MicroMatrixOrg** [comment]
> @MicroMatrixOrg 百度的提交有用吗？我看百度里面没有我的任何提交记录，一周了都~

我没弄百度的提交

**Comment by Erzbir** [comment]
> @MicroMatrixOrg 百度的提交有用吗？我看百度里面没有我的任何提交记录，一周了都~

可以新开一个issue

**Comment by Erzbir** [comment]
> 我是直接设置在docker-compose.yml文件中的
> 
> ```json
>     environment:
>       - http_proxy=http://172.17.0.1:8889
>       - https_proxy=http://172.17.0.1:8889
> ```
> 
> `http://172.17.0.1`是docker的ip，我是先宿主机开代理，然后再给docker代理。服务器挂代理的[文章1](https://blog.micromatrix.cf/archives/VXY32avW) [文章2](https://micromatrix.eu.org/article/20231109)

你这样的代理设置不合理

可以新开一个issue把日志发给我，也许是你的谷歌凭据不正确或者没有在 Google Search Console 中添加权限用户权限

**Comment by MicroMatrixOrg** [comment]
> > 我是直接设置在docker-compose.yml文件中的
> > ```json
> >     environment:
> >       - http_proxy=http://172.17.0.1:8889
> >       - https_proxy=http://172.17.0.1:8889
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `http://172.17.0.1`是docker的ip，我是先宿主机开代理，然后再给docker代理。服务器挂代理的[文章1](https://blog.micromatrix.cf/archives/VXY32avW) [文章2](https://micromatrix.eu.org/article/20231109)
> 
> 你这样的代理设置不合理
> 
> 可以新开一个issue把日志发给我，也许是你的谷歌凭据不正确或者没有在 Google Search Console 中添加权限用户权限

2024-01-09T12:48:03.804+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.AbstractPushStrategy      : Push exception: null
2024-01-09T12:48:05.501+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.GooglePushStrategy        : Pushing to google webmasters: https://blog.micromatrix.cf/archives/u8KjExVH
2024-01-09T12:48:05.522+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.AbstractPushStrategy      : Push exception: null
2024-01-09T12:53:28.742+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.GooglePushStrategy        : Pushing to google webmasters: https://blog.micromatrix.cf/archives/YbfCqQbR
2024-01-09T12:53:28.755+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.AbstractPushStrategy      : Push exception: null
2024-01-09T12:57:10.259+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.GooglePushStrategy        : Pushing to google webmasters: https://blog.micromatrix.cf/archives/YbfCqQbR
2024-01-09T12:57:10.274+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.AbstractPushStrategy      : Push exception: null
2024-01-09T12:58:03.114+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.GooglePushStrategy        : Pushing to google webmasters: https://blog.micromatrix.cf/archives/M1OClCUm
2024-01-09T12:58:03.125+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.AbstractPushStrategy      : Push exception: null
2024-01-09T12:58:03.277+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.GooglePushStrategy        : Pushing to google webmasters: https://blog.micromatrix.cf/archives/YXGBB9zr
2024-01-09T12:58:03.289+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.AbstractPushStrategy      : Push exception: null
2024-01-09T12:58:03.435+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.GooglePushStrategy        : Pushing to google webmasters: https://blog.micromatrix.cf/archives/EQ6kMgW1
2024-01-09T12:58:03.446+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.AbstractPushStrategy      : Push exception: null
2024-01-09T12:58:03.515+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.GooglePushStrategy        : Pushing to google webmasters: https://blog.micromatrix.cf/archives/LXtQ1vYq
2024-01-09T12:58:03.526+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.AbstractPushStrategy      : Push exception: null
2024-01-09T12:58:03.897+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.GooglePushStrategy        : Pushing to google webmasters: https://blog.micromatrix.cf/archives/YbfCqQbR
2024-01-09T12:58:03.907+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.AbstractPushStrategy      : Push exception: null
2024-01-09T12:58:05.604+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.GooglePushStrategy        : Pushing to google webmasters: https://blog.micromatrix.cf/archives/u8KjExVH
2024-01-09T12:58:05.628+08:00  INFO 7 --- [com.stonewu.sitepush.reconciler.PostPushReconciler-t-1] c.s.s.strategy.AbstractPushStrategy      : Push exception: null

**Comment by MicroMatrixOrg** [comment]
> > 我是直接设置在docker-compose.yml文件中的
> > ```json
> >     environment:
> >       - http_proxy=http://172.17.0.1:8889
> >       - https_proxy=http://172.17.0.1:8889
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `http://172.17.0.1`是docker的ip，我是先宿主机开代理，然后再给docker代理。服务器挂代理的[文章1](https://blog.micromatrix.cf/archives/VXY32avW) [文章2](https://micromatrix.eu.org/article/20231109)
> 
> 你这样的代理设置不合理
> 
> 可以新开一个issue把日志发给我，也许是你的谷歌凭据不正确或者没有在 Google Search Console 中添加权限用户权限

那你怎么设置代理的？

**Comment by Erzbir** [comment]
> 那你怎么设置代理的？

实际上不需要进行设置, 因为你是本地的代理

**Comment by adozhao** [comment]
@MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了

**Comment by MicroMatrixOrg** [comment]
> @MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了

你应该做了些啥吧，我的都一个月了，就收录了一个网站的主页。我的博客http://blog.micromatrix.cf/

**Comment by adozhao** [comment]
> > @MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了
> 
> 你应该做了些啥吧，我的都一个月了，就收录了一个网站的主页。我的博客http://blog.micromatrix.cf/

真的啥都没干，目前可以做优化的我觉得你可以主动向google提交你的sidemap.xm

**Comment by MicroMatrixOrg** [comment]
> > > @MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了
> > 
> > 
> > 你应该做了些啥吧，我的都一个月了，就收录了一个网站的主页。我的博客http://blog.micromatrix.cf/
> 
> 真的啥都没干，目前可以做优化的我觉得你可以主动向google提交你的sidemap.xm

你服务器和域名大概是什么，我不知道是不是服务器和域名的问题

**Comment by adozhao** [comment]
> > > > @MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了
> > > 
> > > 
> > > 你应该做了些啥吧，我的都一个月了，就收录了一个网站的主页。我的博客http://blog.micromatrix.cf/
> > 
> > 
> > 真的啥都没干，目前可以做优化的我觉得你可以主动向google提交你的sidemap.xm
> 
> 你服务器和域名大概是什么，我不知道是不是服务器和域名的问题，因为我提交了sidemap.xml但是Google说无法识别
ado.zone                                          sitemap: ado.zone/sitemap.xml

**Comment by MicroMatrixOrg** [comment]
> > > > > @MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了
> > > > 
> > > > 
> > > > 你应该做了些啥吧，我的都一个月了，就收录了一个网站的主页。我的博客http://blog.micromatrix.cf/
> > > 
> > > 
> > > 真的啥都没干，目前可以做优化的我觉得你可以主动向google提交你的sidemap.xm
> > 
> > 
> > 你服务器和域名大概是什么，我不知道是不是服务器和域名的问题，因为我提交了sidemap.xml但是Google说无法识别
> > ado.zone                                          sitemap: ado.zone/sitemap.xml

确定了是域名的问题，市面上的免费域名导致的

**Comment by adozhao** [comment]
> > > > > > @MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了
> > > > > 
> > > > > 
> > > > > 你应该做了些啥吧，我的都一个月了，就收录了一个网站的主页。我的博客http://blog.micromatrix.cf/
> > > > 
> > > > 
> > > > 真的啥都没干，目前可以做优化的我觉得你可以主动向google提交你的sidemap.xm
> > > 
> > > 
> > > 你服务器和域名大概是什么，我不知道是不是服务器和域名的问题，因为我提交了sidemap.xml但是Google说无法识别
> > > ado.zone                                          sitemap: ado.zone/sitemap.xml
> 
> 确定了是域名的问题，市面上的免费域名导致的

每天都会自动索引sitemap一次，香的很~
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/23180747/427d20e4-cd28-41e2-ad20-56ecd001e0bf)

**Comment by MicroMatrixOrg** [comment]
> > > > > > > @MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了
> > > > > > 
> > > > > > 
> > > > > > 你应该做了些啥吧，我的都一个月了，就收录了一个网站的主页。我的博客http://blog.micromatrix.cf/
> > > > > 
> > > > > 
> > > > > 真的啥都没干，目前可以做优化的我觉得你可以主动向google提交你的sidemap.xm
> > > > 
> > > > 
> > > > 你服务器和域名大概是什么，我不知道是不是服务器和域名的问题，因为我提交了sidemap.xml但是Google说无法识别
> > > > ado.zone                                          sitemap: ado.zone/sitemap.xml
> > 
> > 
> > 确定了是域名的问题，市面上的免费域名导致的
> 
> 每天都会自动索引sitemap一次，香的很~ ![image](https://private-user-images.githubusercontent.com/23180747/296118948-427d20e4-cd28-41e2-ad20-56ecd001e0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzQ1MTMsIm5iZiI6MTcwNTQ3NDIxMywicGF0aCI6Ii8yMzE4MDc0Ny8yOTYxMTg5NDgtNDI3ZDIwZTQtY2QyOC00MWUyLWFkMjAtNTZlY2QwMDFlMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA2NTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMTZkNTY5NWIwN2JlYTU1MzExNDEzOGYwZGU5NjMxY2UyNThiMDBiNzY3MjU4NWMwYjBjMzlmYmZiYTM0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1SG5A82wr6O5RCmSl9py_HKJYUjblS4B-so5MQrSyEE)


每天一次你咋做到的

**Comment by adozhao** [comment]
> > > > > > > > @MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了
> > > > > > > 
> > > > > > > 
> > > > > > > 你应该做了些啥吧，我的都一个月了，就收录了一个网站的主页。我的博客http://blog.micromatrix.cf/
> > > > > > 
> > > > > > 
> > > > > > 真的啥都没干，目前可以做优化的我觉得你可以主动向google提交你的sidemap.xm
> > > > > 
> > > > > 
> > > > > 你服务器和域名大概是什么，我不知道是不是服务器和域名的问题，因为我提交了sidemap.xml但是Google说无法识别
> > > > > ado.zone                                          sitemap: ado.zone/sitemap.xml
> > > 
> > > 
> > > 确定了是域名的问题，市面上的免费域名导致的
> > 
> > 
> > 每天都会自动索引sitemap一次，香的很~ ![image](https://private-user-images.githubusercontent.com/23180747/296118948-427d20e4-cd28-41e2-ad20-56ecd001e0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzQ1MTMsIm5iZiI6MTcwNTQ3NDIxMywicGF0aCI6Ii8yMzE4MDc0Ny8yOTYxMTg5NDgtNDI3ZDIwZTQtY2QyOC00MWUyLWFkMjAtNTZlY2QwMDFlMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA2NTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMTZkNTY5NWIwN2JlYTU1MzExNDEzOGYwZGU5NjMxY2UyNThiMDBiNzY3MjU4NWMwYjBjMzlmYmZiYTM0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1SG5A82wr6O5RCmSl9py_HKJYUjblS4B-so5MQrSyEE)
> 
> 每天一次你咋做到的

google自动检索sitemap.xml文件的，如果连续来了好多天sitemap都没有变动，会增加自动检索频率的，不能人为干涉，你提交一次你的sitemap地址就行

**Comment by MicroMatrixOrg** [comment]
> > > > > > > > > @MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你应该做了些啥吧，我的都一个月了，就收录了一个网站的主页。我的博客http://blog.micromatrix.cf/
> > > > > > > 
> > > > > > > 
> > > > > > > 真的啥都没干，目前可以做优化的我觉得你可以主动向google提交你的sidemap.xm
> > > > > > 
> > > > > > 
> > > > > > 你服务器和域名大概是什么，我不知道是不是服务器和域名的问题，因为我提交了sidemap.xml但是Google说无法识别
> > > > > > ado.zone                                          sitemap: ado.zone/sitemap.xml
> > > > 
> > > > 
> > > > 确定了是域名的问题，市面上的免费域名导致的
> > > 
> > > 
> > > 每天都会自动索引sitemap一次，香的很~ ![image](https://private-user-images.githubusercontent.com/23180747/296118948-427d20e4-cd28-41e2-ad20-56ecd001e0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzQ1MTMsIm5iZiI6MTcwNTQ3NDIxMywicGF0aCI6Ii8yMzE4MDc0Ny8yOTYxMTg5NDgtNDI3ZDIwZTQtY2QyOC00MWUyLWFkMjAtNTZlY2QwMDFlMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA2NTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMTZkNTY5NWIwN2JlYTU1MzExNDEzOGYwZGU5NjMxY2UyNThiMDBiNzY3MjU4NWMwYjBjMzlmYmZiYTM0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1SG5A82wr6O5RCmSl9py_HKJYUjblS4B-so5MQrSyEE)
> > 
> > 
> > 每天一次你咋做到的
> 
> google自动检索sitemap.xml文件的，如果连续来了好多天sitemap都没有变动，会增加自动检索频率的，不能人为干涉，你提交一次你的sitemap地址就行

哦哦，我现在买了域名，他能识别了。全部都收录了

**Comment by adozhao** [comment]
> > > > > > > > > > @MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 你应该做了些啥吧，我的都一个月了，就收录了一个网站的主页。我的博客http://blog.micromatrix.cf/
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 真的啥都没干，目前可以做优化的我觉得你可以主动向google提交你的sidemap.xm
> > > > > > > 
> > > > > > > 
> > > > > > > 你服务器和域名大概是什么，我不知道是不是服务器和域名的问题，因为我提交了sidemap.xml但是Google说无法识别
> > > > > > > ado.zone                                          sitemap: ado.zone/sitemap.xml
> > > > > 
> > > > > 
> > > > > 确定了是域名的问题，市面上的免费域名导致的
> > > > 
> > > > 
> > > > 每天都会自动索引sitemap一次，香的很~ ![image](https://private-user-images.githubusercontent.com/23180747/296118948-427d20e4-cd28-41e2-ad20-56ecd001e0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzQ1MTMsIm5iZiI6MTcwNTQ3NDIxMywicGF0aCI6Ii8yMzE4MDc0Ny8yOTYxMTg5NDgtNDI3ZDIwZTQtY2QyOC00MWUyLWFkMjAtNTZlY2QwMDFlMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA2NTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMTZkNTY5NWIwN2JlYTU1MzExNDEzOGYwZGU5NjMxY2UyNThiMDBiNzY3MjU4NWMwYjBjMzlmYmZiYTM0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1SG5A82wr6O5RCmSl9py_HKJYUjblS4B-so5MQrSyEE)
> > > 
> > > 
> > > 每天一次你咋做到的
> > 
> > 
> > google自动检索sitemap.xml文件的，如果连续来了好多天sitemap都没有变动，会增加自动检索频率的，不能人为干涉，你提交一次你的sitemap地址就行
> 
> 哦哦，我现在买了域名，他能识别了。全部都收录了

新域名是啥，我进去观摩观摩

**Comment by MicroMatrixOrg** [comment]
> > > > > > > > > > > @MicroMatrixOrg 我觉得谷歌没必要特别做优化，我的啥都没干，全部自动收录了
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 你应该做了些啥吧，我的都一个月了，就收录了一个网站的主页。我的博客http://blog.micromatrix.cf/
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 真的啥都没干，目前可以做优化的我觉得你可以主动向google提交你的sidemap.xm
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你服务器和域名大概是什么，我不知道是不是服务器和域名的问题，因为我提交了sidemap.xml但是Google说无法识别
> > > > > > > > ado.zone                                          sitemap: ado.zone/sitemap.xml
> > > > > > 
> > > > > > 
> > > > > > 确定了是域名的问题，市面上的免费域名导致的
> > > > > 
> > > > > 
> > > > > 每天都会自动索引sitemap一次，香的很~ ![image](https://private-user-images.githubusercontent.com/23180747/296118948-427d20e4-cd28-41e2-ad20-56ecd001e0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzQ1MTMsIm5iZiI6MTcwNTQ3NDIxMywicGF0aCI6Ii8yMzE4MDc0Ny8yOTYxMTg5NDgtNDI3ZDIwZTQtY2QyOC00MWUyLWFkMjAtNTZlY2QwMDFlMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA2NTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMTZkNTY5NWIwN2JlYTU1MzExNDEzOGYwZGU5NjMxY2UyNThiMDBiNzY3MjU4NWMwYjBjMzlmYmZiYTM0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1SG5A82wr6O5RCmSl9py_HKJYUjblS4B-so5MQrSyEE)
> > > > 
> > > > 
> > > > 每天一次你咋做到的
> > > 
> > > 
> > > google自动检索sitemap.xml文件的，如果连续来了好多天sitemap都没有变动，会增加自动检索频率的，不能人为干涉，你提交一次你的sitemap地址就行
> > 
> > 
> > 哦哦，我现在买了域名，他能识别了。全部都收录了
> 
> 新域名是啥，我进去观摩观摩

blog.micromatrix.org
