### ISSUE TITLE
百度后台查询没有提交记录

### ISSUE THREAD

**Issue by adozhao** [Stonewuu/halo-plugin-sitepush#40]
插件显示百度都是提交成功的，然而进了后台查询没有提交记录，大概提交十天左右了吧
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/23180747/58c08577-de98-44c6-9587-871b479ccf30)

bing的提交倒是正常~

**Comment by Erzbir** [comment]
已修复

**Comment by adozhao** [comment]
> 已修复

辛苦了 🌹
请问已经提交的已计入数据库，插件更新之后是否会重新进行提交一次呢？

**Comment by Erzbir** [comment]
> > 已修复
> 
> 辛苦了 🌹 请问已经提交的已计入数据库，插件更新之后是否会重新进行提交一次呢？

应该不会，只要数据库里成功的记录就不会提交对应的链接，不过不排除数据库数据丢失的情况

**Comment by Erzbir** [comment]
> > > > 已修复
> > > 
> > > 
> > > 辛苦了 🌹 请问已经提交的已计入数据库，插件更新之后是否会重新进行提交一次呢？
> > 
> > 
> > 应该不会，只要数据库里成功的记录就不会提交对应的链接，不过不排除数据库数据丢失的情况
> 
> 那就存在老数据无法重新提交的兼容性的问题了

详细描述下呢

**Comment by adozhao** [comment]
> > > > > 已修复
> > > > 
> > > > 
> > > > 辛苦了 🌹 请问已经提交的已计入数据库，插件更新之后是否会重新进行提交一次呢？
> > > 
> > > 
> > > 应该不会，只要数据库里成功的记录就不会提交对应的链接，不过不排除数据库数据丢失的情况
> > 
> > 
> > 那就存在老数据无法重新提交的兼容性的问题了
> 
> 详细描述下呢

我之前所有的文章百度全部提交成功，但是因为之前插件有bug，百度并没有收到相关提交。那么随着此bug修复之后，因为之前提交全部是成功的，并已记入数据库，因此即使插件更新之后，也无法把之前”假提交成功“的文章重新提交了~

**Comment by Erzbir** [comment]
> 我之前所有的文章百度全部提交成功（实际因插件BUG没成功），但是因为之前插件有bug，百度并没有收到相关提交。那么随着此bug修复之后，因为之前提交全部是成功的，并已记入数据库，因此即使插件更新之后，也无法把之前”假提交成功“的文章重新提交了~

那可以考虑新增一个重新提交的功能

**Comment by adozhao** [comment]
> > 我之前所有的文章百度全部提交成功（实际因插件BUG没成功），但是因为之前插件有bug，百度并没有收到相关提交。那么随着此bug修复之后，因为之前提交全部是成功的，并已记入数据库，因此即使插件更新之后，也无法把之前”假提交成功“的文章重新提交了~
> 
> 那可以考虑新增一个重新提交的功能

是滴，否则就要手动删库了，容易出问题
