### ISSUE TITLE
百度和bing推送失败，谷歌没有推送日志

### ISSUE THREAD

**Issue by Dominic-KK** [Stonewuu/halo-plugin-sitepush#54]
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/76522991/a04ac52b-523d-4d83-bee5-cf0b264f1025)

**Comment by Dominic-KK** [comment]
很抱歉我有点小白，这里的日志应该怎么获取

**Comment by Erzbir** [comment]
> 很抱歉我有点小白，这里的日志应该怎么获取

在概览中下载运行日志

**Comment by Dominic-KK** [comment]
[halo-log-2024-01-12 21_53.log](https://github.com/Stonewuu/halo-plugin-sitepush/files/13919875/halo-log-2024-01-12.21_53.log)

**Comment by Dominic-KK** [comment]
另外，最新的1.4.1版本在商店更新不上，点了更新之后转圈，然后没任何反应，还是显示1.4.0版本

**Comment by Erzbir** [comment]
> [halo-log-2024-01-12 21_53.log](https://github.com/Stonewuu/halo-plugin-sitepush/files/13919875/halo-log-2024-01-12.21_53.log)

日志显示是你提交额度用完了

**Comment by Erzbir** [comment]
> 另外，最新的1.4.1版本在商店更新不上，点了更新之后转圈，然后没任何反应，还是显示1.4.0版本

这个是因为我把版本号写错了，再联系halo官方处理

**Comment by Dominic-KK** [comment]
这样啊，谷歌也是额度完了是吗

**Comment by Dominic-KK** [comment]
那我明天再看推送情况，没问题就可以关闭了

**Comment by Dominic-KK** [comment]
那不会吧，服务器是香港的，可以ping谷歌，1.3.9版本也可以正常提交谷歌

**Comment by Erzbir** [comment]
> 那不会吧，服务器是香港的，可以ping谷歌，1.3.9版本也可以正常提交谷歌

ping一下这个看看: indexing.googleapis.com

**Comment by Dominic-KK** [comment]
```shell
ping indexing.googleapis.com -c4
PING indexing.googleapis.com (172.217.24.106) 56(84) bytes of data.
64 bytes from sin10s07-in-f106.1e100.net (172.217.24.106): icmp_seq=1 ttl=109 time=647 ms
64 bytes from sin10s07-in-f106.1e100.net (172.217.24.106): icmp_seq=2 ttl=109 time=716 ms
64 bytes from sin10s07-in-f106.1e100.net (172.217.24.106): icmp_seq=3 ttl=109 time=719 ms
64 bytes from sin10s07-in-f106.1e100.net (172.217.24.106): icmp_seq=4 ttl=109 time=680 ms

--- indexing.googleapis.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3256ms
rtt min/avg/max/mdev = 647.706/690.921/719.398/29.360 ms
```

**Comment by Erzbir** [comment]
> ```shell
> ping indexing.googleapis.com -c4
> PING indexing.googleapis.com (172.217.24.106) 56(84) bytes of data.
> 64 bytes from sin10s07-in-f106.1e100.net (172.217.24.106): icmp_seq=1 ttl=109 time=647 ms
> 64 bytes from sin10s07-in-f106.1e100.net (172.217.24.106): icmp_seq=2 ttl=109 time=716 ms
> 64 bytes from sin10s07-in-f106.1e100.net (172.217.24.106): icmp_seq=3 ttl=109 time=719 ms
> 64 bytes from sin10s07-in-f106.1e100.net (172.217.24.106): icmp_seq=4 ttl=109 time=680 ms
> 
> --- indexing.googleapis.com ping statistics ---
> 4 packets transmitted, 4 received, 0% packet loss, time 3256ms
> rtt min/avg/max/mdev = 647.706/690.921/719.398/29.360 ms
> ```

我这边谷歌是正常的，可能是超时了，看你ping的延迟也有可能是超时了

**Comment by Erzbir** [comment]
谷歌没有推送日志的问题已将解决: #59
