### ISSUE TITLE
更改了文章别名不会重新推送！

### ISSUE THREAD

**Issue by UPToZ-Core** [Stonewuu/halo-plugin-sitepush#55]
halo文章是根据文章别名进行生成访问链接的，如果更改了文章别名重新保存文章或者发布，推送就无法推送正确的文章访问路径了。

**Comment by Erzbir** [comment]
> halo文章是根据文章别名进行生成访问链接的，如果更改了文章别名重新保存文章或者发布，推送就无法推送正确的文章访问路径了。

如果你改名就会在进行一次推送

**Comment by Erzbir** [comment]
> 我的建议是只要别名或者名字进行了变化就重新进行一次推送。

目前确实是改名之后会触发推送，但是可能会获取到旧的文章推送，这个我想办法保证获取到新的

**Comment by Erzbir** [comment]
目前采用了一种暂时的策略来解决, 等待 halo 提供事件机制再用捕获事件的方式重构 #57
