### ISSUE TITLE
插件设置建议对输入加上 .trim() 函数校验

### ISSUE THREAD

**Issue by QYunChao** [Stonewuu/halo-plugin-sitepush#61]
之前安装插件配置好后就一直等着自动推送，结果一直失败：
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/10084197/bc707c23-7eac-489a-8ac6-e8dab1963951)
查了好久才发现是输入的网站前面多了一个空格，所以提一下建议~

**Comment by Erzbir** [comment]
这个是老版本了吧，更新版本试试看
