### ISSUE TITLE
显示推送成功，但是搜索引擎搜不到站点

### ISSUE THREAD

**Issue by Dominic-KK** [Stonewuu/halo-plugin-sitepush#64]
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/76522991/3f5275e3-0b07-4d2d-9225-28e215959040)
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/76522991/f63f62a4-7781-45f0-8f2b-6aff3f8da1fd)
还特意多等了几天

**Comment by Erzbir** [comment]
并不是推送了就会立马收录了，具体看百度，只要是百度的控制台中有api的推送记录就是正常的
