### ISSUE TITLE
推送日志页面的请求一直失败

### ISSUE THREAD

**Issue by leeyin98** [Stonewuu/halo-plugin-sitepush#65]
Halo：v2.11.3
站点推送插件：v1.4.3

大概从上星期开始，我的推送日志页面就打不开了，看请求一直都失败的：
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/39760117/75405f3b-ec2e-40dc-9a46-5739819e2f5c)

后台日志没看到有对应的报错信息，推送功能应该是正常的：
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/39760117/cc340b6a-9500-4bb2-b44d-87918d54c4c2)

我把请求url直接丢网页上过个10秒也会显示出数据：
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/39760117/fd132559-70c1-4e3f-a0c5-fa96a7876ce3)

**Comment by Erzbir** [comment]
是不是日志太多超时了？

**Comment by leeyin98** [comment]
> 是不是超时了？

看日志是36条，感觉应该不至于超时吧。
请问您知道Halo有针对超时时间的配置吗，或者您觉得这个超时是在哪个层面的呢

**Comment by leeyin98** [comment]
> Halo：v2.11.3 站点推送插件：v1.4.3
> 
> 大概从上星期开始，我的推送日志页面就打不开了，看请求一直都失败的： ![image](https://private-user-images.githubusercontent.com/39760117/302079497-75405f3b-ec2e-40dc-9a46-5739819e2f5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMjYwNjgsIm5iZiI6MTcwNzAyNTc2OCwicGF0aCI6Ii8zOTc2MDExNy8zMDIwNzk0OTctNzU0MDVmM2ItZWMyZS00MGRjLTlhNDYtNTczOTgxOWUyZjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA1NDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNjc3ZGExMmEwNmJhZTFmNzdkZDVjMThhZWM4ZTJiNGZlMjg2ZmJjYzhkMDA4MTg1OWVhMWRmM2ExODg0NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zr3Y93duYv7Ew-v_lzOMLJupADnTNgaKlQaOtBN5Vrs)
> 
> 后台日志没看到有对应的报错信息，推送功能应该是正常的： ![image](https://private-user-images.githubusercontent.com/39760117/302079832-cc340b6a-9500-4bb2-b44d-87918d54c4c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMjYwNjgsIm5iZiI6MTcwNzAyNTc2OCwicGF0aCI6Ii8zOTc2MDExNy8zMDIwNzk4MzItY2MzNDBiNmEtOTUwMC00YmIyLWI0NGQtODc5MThkNTRjNGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA1NDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMDgzMTM1YmQ0YWJjOGIwY2M3M2UwMGRjZDdkYTgwYWFlZjk4MjI5ZDdhYWZmNTc5ZTFkYzhjMTBiMTQ1N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UbHY48PLjcPutx0ef-6qVXFMIPVSD_1HJqya2B7DAAg)
> 
> 我把请求url直接丢网页上过个10秒也会显示出数据： ![image](https://private-user-images.githubusercontent.com/39760117/302079687-fd132559-70c1-4e3f-a0c5-fa96a7876ce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMjYwNjgsIm5iZiI6MTcwNzAyNTc2OCwicGF0aCI6Ii8zOTc2MDExNy8zMDIwNzk2ODctZmQxMzI1NTktNzBjMS00ZTNmLWEwYzUtZmE5NmE3ODc2Y2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA1NDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMWNiMWRkMGI4ZWQ2MWFkOWRkZjQ3ODUwMzZlNmU0NGQyMWUyYmVjYzE2YzEzN2I3OTg1NmRiNzBiNTA1NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fnwDCb8s4qXQ-Wkykb8L4-5l7sJVC55OtEMaL8ZEuRY)

我尝试使用页面上的清空操作，同样也是请求失败。

**Comment by leeyin98** [comment]
我尝试使用页面上的清空操作，同样也是请求失败。

尝试卸载插件重新安装也未解决该问题。

**Comment by Erzbir** [comment]
> 我尝试使用页面上的清空操作，同样也是请求失败。

可能是插件本身的超时时间设置得太小。

你那边可以打包吗？如果可以，可以先自行尝试修改一下console/api/request.ts文件中的timeout后编译打包安装。要等晚上我才有时间。

**Comment by leeyin98** [comment]
> > 我尝试使用页面上的清空操作，同样也是请求失败。
> 
> 可能是插件本身的超时时间设置得太小。
> 
> 你那边可以打包吗？如果可以，可以先自行尝试修改一下console/api/request.ts文件中的timeout后编译打包安装。非常欢迎直接pr。要等晚上我才有时间。

打包安装确实没试过，我去研究下吧，能解决的话我就提个pr，以及timeout您觉得改为多长时间更为合适。

**Comment by leeyin98** [comment]
确实是日志量太大导致超时的，不是36条，日志量是4036条。
