### ISSUE TITLE
百度推送，一直返回失败记录

### ISSUE THREAD

**Issue by FunkyGod** [Stonewuu/halo-plugin-sitepush#70]
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/39259580/045be076-a225-498f-a46d-7e7e5243f141)
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/39259580/2e4a0d97-24cf-40dc-9d45-612060f66502)
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/39259580/06fc0359-0370-4787-9bb7-aff29ca6a60a)
请教一下，需要怎么解决呢

**Comment by Erzbir** [comment]
将鼠标移动到黄点可以查看失败原因

**Comment by FunkyGod** [comment]
> 将鼠标移动到黄点可以查看失败原因

![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/39259580/d9146be0-46f9-4989-bc87-20dd8e0a270b)
这是超出推送容量了么？

**Comment by Erzbir** [comment]
> > 将鼠标移动到黄点可以查看失败原因
> 
> 
> 这是超出推送容量了么？

是的

**Comment by FunkyGod** [comment]
有好的解决思路吗🤔





------------------ 原始邮件 ------------------
发件人: Erzbir ***@***.***&gt;
发送时间: 2024年2月19日 22:50
收件人: 1131633198 ***@***.***&gt;
主题: Re: [Stonewuu/halo-plugin-sitepush] 百度推送，一直返回失败记录 (Issue #70)





   
将鼠标移动到黄点可以查看失败原因
  
这是超出推送容量了么？
  
是的

**Comment by Erzbir** [comment]
> 有好的解决思路吗🤔
百度的推送额度实在太少, 百度建议在百度的控制台提交 sitemap 让它进行抓取
