### ISSUE TITLE
求助！国内腾讯云服务器怎么推送到谷歌

### ISSUE THREAD

**Issue by YusCoding** [Stonewuu/halo-plugin-sitepush#74]
很抱歉这是一个与项目本身无关的问题，但是我莫得办法了也是。如题，我服务器推送谷歌一直连接超时，这个代理怎么配置啊，我本地是有clash这种东西的走的trojan，但是服务器代理怎么配置哇。。。有没有大佬救救弟弟！

**Comment by Erzbir** [comment]
> 很抱歉这是一个与项目本身无关的问题，但是我莫得办法了也是。如题，我服务器推送谷歌一直连接超时，这个代理怎么配置啊，我本地是有clash这种东西的走的trojan，但是服务器代理怎么配置哇。。。有没有大佬救救弟弟！

ping 谷歌能 ping 通的话，大概就是配置没对

**Comment by YusCoding** [comment]
可能我描述问题，我说的本地是我的电脑，我电脑有clash，然后想知道怎么让服务器也能爬，要在服务器装个类似软件吗。服务器目前ping谷歌肯定是ping不通的

**Comment by YusCoding** [comment]
> > 很抱歉这是一个与项目本身无关的问题，但是我莫得办法了也是。如题，我服务器推送谷歌一直连接超时，这个代理怎么配置啊，我本地是有clash这种东西的走的trojan，但是服务器代理怎么配置哇。。。有没有大佬救救弟弟！
> 
> ping 谷歌能 ping 通的话，大概就是配置没对

可能我描述问题，我说的本地是我的电脑，我电脑有clash，然后想知道怎么让服务器也能爬，要在服务器装个类似软件吗。服务器目前ping谷歌肯定是ping不通的

**Comment by Erzbir** [comment]
> 
> 可能我描述问题，我说的本地是我的电脑，我电脑有clash，然后想知道怎么让服务器也能爬，要在服务器装个类似软件吗。服务器目前ping谷歌肯定是ping不通的

看对应系统的代理工具如何安装使用

**Comment by YusCoding** [comment]
> > 可能我描述问题，我说的本地是我的电脑，我电脑有clash，然后想知道怎么让服务器也能爬，要在服务器装个类似软件吗。服务器目前ping谷歌肯定是ping不通的
> 
> 看对应系统的代理工具如何安装使用

好的多谢！
