### ISSUE TITLE
配置页面数据凭据json偶发不展示；必应不推送

### ISSUE THREAD

**Issue by YusCoding** [Stonewuu/halo-plugin-sitepush#75]
环境：halo2.12.4，centos7 docker-compose修改数据库为mysql后部署，主题earth1.7.1，推送插件版本1.4.5。

问题一：站点推送页面我配置了谷歌推送凭据json，但是会经常切换到‘谷歌收录于推送’tab栏时候出现文本框没有内容问题，然后切换到别的tab栏比如必应收录推送然后再切回来又出现了，F12确认页面加载时后端响应数据是存在的，只是前端未展示
问题二（已解决，应该是由于代理安装完成后docker服务未重启，现在已经能够正常推送）：如下图，谷歌推送全都报错，不曾成功
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/33707489/a6303e4b-0019-4b4b-91aa-d712aa7fe4c0)
问题三：似乎必应不再推送了，因为我只配置了谷歌+必应，然后之前是必应成功谷歌time out，现在必应不推了谷歌报错，不确定这个是否正常，以上！

期待您的回复！

**Comment by Erzbir** [comment]
重启之后会推送吗

**Comment by Erzbir** [comment]
谷歌看起来像是网络问题

**Comment by Erzbir** [comment]
<img width="609" alt="截屏2024-03-12 09 56 06" src="https://github.com/Stonewuu/halo-plugin-sitepush/assets/100007608/8efcd863-3de1-4f55-abcf-3fb48eacc12b">

**Comment by YusCoding** [comment]
> 重启之后会推送吗

重启插件会推送。全都会推

**Comment by YusCoding** [comment]
> 谷歌看起来像是网络问题

谷歌问题已解决，应该是装完代理工具后没重启halo的docker导致

**Comment by Erzbir** [comment]
> 
> 这个重试不是定时推送任务而且定时重试推送失败的任务吗

这个重试是重新推送失败的任务

**Comment by YusCoding** [comment]
> > 这个重试不是定时推送任务而且定时重试推送失败的任务吗
> 
> 这个重试是重新推送失败的任务

好的！感谢回复！那我知道为什么没有bing推送了，因为之前bing推送和重试日志被我删除了，所以之后就只重试失败的谷歌任务了
