### ISSUE TITLE
可否设定不同api的网站不同

### ISSUE THREAD

**Issue by HowieHz** [Stonewuu/halo-plugin-sitepush#76]
如题，我baidu api是www.howiehz.top（**baidu，没www还不行了
谷歌和bing是howiehz.top
但是只能设置一个api

**Comment by Erzbir** [comment]
我的百度是可以不用 www 的, 也许是你验证有问题

**Comment by HowieHz** [comment]
> 我的百度是可以不用 www 的, 也许是你验证有问题

试了试，可以直接用howiehz.top了
