### ISSUE TITLE
建议优化清除日志功能，目前日志较多无法清除

### ISSUE THREAD

**Issue by CV-Devlau** [Stonewuu/halo-plugin-sitepush#77]
因为百度推送报错的原因目前，日志有20000条，清除功能接口超时，halo会强制停止，并且卸载也不会清除日志

**Comment by Erzbir** [comment]
会抽空加上这个功能

**Comment by ruibaby** [comment]
建议优化一下推送策略和记录保留条数，现在太容易造成过量的无效数据。

<img width="920" alt="image" src="https://github.com/Stonewuu/halo-plugin-sitepush/assets/21301288/23f51406-9173-419b-be28-acd8442707ed">

**Comment by ruibaby** [comment]
Hi @Erzbir @Stonewuu ，在这个问题解决之前，我们决定先从 [Halo 应用市场](https://www.halo.run/store/apps) 下架，因为这个插件可能会导致用户数据库产生大量数据，从而影响到部分功能的正常使用（比如备份恢复，目前这个数据量 Halo 无法正常应对）。

如果在修改方式上有任何需要帮助的，可以直接在这个 issue 上交流。

**Comment by Erzbir** [comment]
> Hi @Erzbir @Stonewuu ，在这个问题解决之前，我们决定先从 [Halo 应用市场](https://www.halo.run/store/apps) 下架，因为这个插件可能会导致用户数据库产生大量数据，从而影响到部分功能的正常使用（比如备份恢复，目前这个数据量 Halo 无法正常应对）。
> 
> 
> 
> 如果在修改方式上有任何需要帮助的话，可以直接在这个 issue 上交流。

那只保留失败日志吧，成功的就不保留，我明天更新一下，最近找工作有点忙

**Comment by Erzbir** [comment]
再增加一个条目限制应该会好点

**Comment by ruibaby** [comment]
我觉得可以同时保留失败和成功的，但是可以添加保留条数和保留天数的设置选项，然后根据这个设置自动删除旧数据。

**Comment by Stonewuu** [comment]
> Hi @Erzbir @Stonewuu ，在这个问题解决之前，我们决定先从 [Halo 应用市场](https://www.halo.run/store/apps) 下架，因为这个插件可能会导致用户数据库产生大量数据，从而影响到部分功能的正常使用（比如备份恢复，目前这个数据量 Halo 无法正常应对）。
> 
> 如果在修改方式上有任何需要帮助的话，可以直接在这个 issue 上交流。

#78 已更新1.4.6版本，新增按时间定时清理的逻辑，条目数量限制如果有需要后续再加上 @ruibaby

**Comment by ruibaby** [comment]
我建议这里默认设置一个值，否则用户更新之后还是需要手动去设置，容易忽略掉。

https://github.com/Stonewuu/halo-plugin-sitepush/blob/81581dfa1b6e5eef30280b1ff6a0ca8ece500a4a/src/main/resources/extensions/settings.yaml#L42

**Comment by Stonewuu** [comment]
> 我建议这里默认设置一个值，否则用户更新之后还是需要手动去设置，容易忽略掉。
> 
> https://github.com/Stonewuu/halo-plugin-sitepush/blob/81581dfa1b6e5eef30280b1ff6a0ca8ece500a4a/src/main/resources/extensions/settings.yaml#L42

删除用户数据这件事本身还是比较敏感，为了避免不必要的麻烦，留给用户自己做选择会好一些

**Comment by Stonewuu** [comment]
> Hi @Erzbir @Stonewuu ，在这个问题解决之前，我们决定先从 [Halo 应用市场](https://www.halo.run/store/apps) 下架，因为这个插件可能会导致用户数据库产生大量数据，从而影响到部分功能的正常使用（比如备份恢复，目前这个数据量 Halo 无法正常应对）。
> 
> 如果在修改方式上有任何需要帮助的话，可以直接在这个 issue 上交流。

目前该问题已解决，能否帮忙重新上架一下应用市场呢？@ruibaby

**Comment by ruibaby** [comment]
> 目前该问题已解决，能否帮忙重新上架一下应用市场呢？@ruibaby

已上架。

**Comment by Stonewuu** [comment]
> > 目前该问题已解决，能否帮忙重新上架一下应用市场呢？@ruibaby
> 
> 已上架。

感谢🙏

**Comment by ruibaby** [comment]
根据用户反馈，这个插件的日志存储仍然可能导致创建大量数据的问题：

<img width="622" alt="image" src="https://github.com/user-attachments/assets/2de9090a-d11d-4c99-834d-60e4235f4372">

**Comment by Stonewuu** [comment]
> 根据用户反馈，这个插件的日志存储仍然可能导致创建大量数据的问题：
> 
> <img alt="image" width="622" src="https://private-user-images.githubusercontent.com/21301288/381809178-2de9090a-d11d-4c99-834d-60e4235f4372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDQ2MjcsIm5iZiI6MTczMDM0NDMyNywicGF0aCI6Ii8yMTMwMTI4OC8zODE4MDkxNzgtMmRlOTA5MGEtZDExZC00Yzk5LTgzNGQtNjBlNDIzNWY0MzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAzMTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNzU4NWQ4OWRmYWQ4YjM0MzI2ODYzN2VmYjg4NDk1ZjYxNzE1N2QzZjNlZGM2OTk4OTEzMzg1YmI4Njg3ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._pS3LefFYAcfZu8WYyoboTO1VDYQIa0ubEGWmyb4TV0">

是已经更新了最新版本的插件吗？

**Comment by acanyo** [comment]
> > 根据用户反馈，这个插件的日志存储仍然可能导致创建大量数据的问题：
> > <img alt="image" width="622" src="https://private-user-images.githubusercontent.com/21301288/381809178-2de9090a-d11d-4c99-834d-60e4235f4372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDQ2MjcsIm5iZiI6MTczMDM0NDMyNywicGF0aCI6Ii8yMTMwMTI4OC8zODE4MDkxNzgtMmRlOTA5MGEtZDExZC00Yzk5LTgzNGQtNjBlNDIzNWY0MzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAzMTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNzU4NWQ4OWRmYWQ4YjM0MzI2ODYzN2VmYjg4NDk1ZjYxNzE1N2QzZjNlZGM2OTk4OTEzMzg1YmI4Njg3ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._pS3LefFYAcfZu8WYyoboTO1VDYQIa0ubEGWmyb4TV0">
> 
> 是已经更新了最新版本的插件吗？

我用的最新版 还是有这个问题存在 已经提了issue #91
