### ISSUE TITLE
优化推送设置

### ISSUE THREAD

**Issue by QingFeng-awa** [Stonewuu/halo-plugin-sitepush#79]
### Halo版本
2.15.0
### 插件版本
1.4.6
## 详细信息
将插件设置中的"是否启用xx推送"的选项移动到最上面,若用户选择关闭,则隐藏下方内容(包含原本在最上方的"是否启用标签验证")。

**Comment by Stonewuu** [comment]
有些用户可能会选择不开启推送的情况下，单独使用标签验证功能，所以两者还是独立的
