### ISSUE TITLE
不支持Google吗？

### ISSUE THREAD

**Issue by nasheep** [Stonewuu/halo-plugin-sitepush#8]
当前插件不支持推送到Google搜索吗？

**Comment by Stonewuu** [comment]
@nasheep 是的目前没有支持Google搜索，但是目前谷歌对于主动推送和sitemap的抓取策略都差不多，可以尝试安装sitemap插件

**Comment by nasheep** [comment]
> @nasheep 是的目前没有支持Google搜索，但是目前谷歌对于主动推送和sitemap的抓取策略都差不多，可以尝试安装sitemap插件

好的，感谢回复
