### ISSUE TITLE
功能增强 避免推送不可见文章

### ISSUE THREAD

**Issue by HowieHz** [Stonewuu/halo-plugin-sitepush#80]
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/94725606/13a3df43-c487-45df-bff9-8517f412ea99)
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/94725606/7d8655d5-ea02-4495-9240-5446cc4089b7)

**Comment by Stonewuu** [comment]
已在1.5.0版本中更新 [1.5.0](https://github.com/Stonewuu/halo-plugin-sitepush/releases/tag/1.5.0)

**Comment by HowieHz** [comment]
> 已在1.5.0版本中更新 [1.5.0](https://github.com/Stonewuu/halo-plugin-sitepush/releases/tag/1.5.0)

👍️更新神速
