### ISSUE TITLE
建议增加一个推送全部文章的btn

### ISSUE THREAD

**Issue by ShiinaKin** [Stonewuu/halo-plugin-sitepush#82]
rt，需求场景是迁移到halo后，使用新的domain，需要重新推送收录

**Comment by Stonewuu** [comment]
这个需求，可以更新到最新版插件，然后把插件设置中的两个清理设置修改为1天，同时关闭重试功能，过一两天后重启插件，这样子就会重新推送了

**Comment by Stonewuu** [comment]
不过使用搜索引擎官方的站点迁移功能应该能更简单的解决这个问题

**Comment by mashirot** [comment]
> 这个需求，可以更新到最新版插件，然后把插件设置中的两个清理设置修改为1天，同时关闭重试功能，过一两天后重启插件，这样子就会重新推送了

实测并未重新推送，还是希望能增加这个功能

**Comment by ShiinaKin** [comment]
see #86
