### ISSUE TITLE
百度推送失败，必应正常

### ISSUE THREAD

**Issue by Dion-Lee** [Stonewuu/halo-plugin-sitepush#9]
百度推送文章一直失败，只有在0点的时候会成功。必应正常
<img width="2044" alt="image" src="https://github.com/Stonewuu/halo-plugin-sitepush/assets/68332968/09f83ed2-7b8b-4f5c-94f0-e990b5e2b7e1">

**Comment by 907739769** [comment]
百度限制了推送数量，看日志就知道了
![image](https://github.com/Stonewuu/halo-plugin-sitepush/assets/27858369/b6f74398-0b0f-48e3-994e-42d4866ac84b)

**Comment by Erzbir** [comment]
没有问题这个 issue 就关闭了
